@server=http://localhost:4004
@username=alice
@password=


### BusinessPartners
# @name BusinessPartners_GET
GET {{server}}/odata/v4/business-partner/BusinessPartnerViewer
Authorization: Basic {{username}}:{{password}}


### BusinessPartners
# @name BusinessPartners_POST
POST {{server}}/odata/v4/business-partner/BusinessPartners
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "businessPartnerUUID": "30448324-31e4-43e7-a906-25e5905891dd",
  "businessPartnerID": "D-30448324",
  "fullData": "fullData-30448324",
  "text": "text-30448324"
}

### Similarity Search
POST {{server}}/odata/v4/business-partner/similaritySearch
Authorization: Basic {{username}}:{{password}}
Content-Type: application/json

{
  "query": "What is the full data of business partner Yasutake?"
}

### Ask a Question
POST {{server}}/odata/v4/business-partner/ask
Authorization: Basic {{username}}:{{password}}
Content-Type: application/json

{
  "query": "Where is Mio Yasutake located?"
}

### Danger! Delete All
POST {{server}}/odata/v4/business-partner/deleteAll
Content-Type: application/json
